### ISSUE TITLE
config gui

### ISSUE THREAD

**Issue by sdaviet** [jomarin38/F3FChrono#119]
below, you can see the new gui :

- first screen standard config :
![image](https://user-images.githubusercontent.com/7544520/84707141-756bb100-af5e-11ea-966c-b0d5e60d2d0d.png)

- base screen :
![image](https://user-images.githubusercontent.com/7544520/84707195-90d6bc00-af5e-11ea-9eb6-2b98755a7e9d.png)

- sound & voice screen :
![image](https://user-images.githubusercontent.com/7544520/84707272-b4016b80-af5e-11ea-9845-922b9b8700e3.png)

- advanced screen :
![image](https://user-images.githubusercontent.com/7544520/84707414-ead78180-af5e-11ea-999d-9796c8dd1f42.png)

your feedback ?

**Comment by jomarin38** [comment]
Seems good 😀
I will have to update the user guide 😉
