### ISSUE TITLE
New Event on database

### ISSUE THREAD

**Issue by sdaviet** [jomarin38/F3FChrono#12]
After add a new event on database (Event and competitor), initialisation data return an error on Event.get_current_round. Variable self.current_round is egal to None.

**Comment by sdaviet** [comment]
I test a new contest with small data on the database insert before.
I add manually a new contest on database with 3 pilots.
When you select this contest in the combobox panel config, you have an error because rounds list is empty. 
is it the GUI or Event job to check and create a round ?

**Comment by jomarin38** [comment]
I will have a look at it this evening.
I think it could be solved together with #14

**Comment by sdaviet** [comment]
exactly ;)
