### ISSUE TITLE
menee issues

### ISSUE THREAD

**Issue by sdaviet** [jomarin38/F3FChrono#136]
issues in french only for discussion

Priorité 1 :
  revol arrêt du chrono. Vérifier sur Vol null.
  dossard de départ jour +1 : vérifier la prise en compte des pilotes présents uniquement. Le round créé le jour précédent doit être annulé.
  Ecran : 
    supprimer temps au tour,
    Agrandir status, temps en cours, + Gras et police ++
    Agrandir bouton + Gras et police ++
    Temps chrono afficher uniquement les secondes durant le run, centième en fin de run

Priorité 2 :
   détection tension basse au démarrage du soft.
   Temps maxi round pour annulation, lancer un chrono à chaque fin de run validé.
   sons : N° de dossard et temps final avec wav,
   Remonter le temps du chrono depuis l'arduino ?
   Interface web : 
     1ere ligne sur fond clair serait plus lisible depuis le téléphone.
 Export
   Envoyer une manche seule sur f3xvault   
 
boitier : 
  connecteur du buzzer à visser.
  Monter la tension du pack d'alimentation permettrait d'avoir un beep plus puissant. Reprendre l'étage d'adaptation de l'entrée analogique.
  Passer les diodes dans le boitier et ajouter une mesure de tension.
  Rendre le boitier etanche ?

Accessoires connectés :
[Anemotre bluetooth](https://www.uni-trend.com/html/product/Environmental/Environmental_Tester/Mini_BT/UT363-BT.html) depuis une application, la messagerie n'est pas dans la doc.
Anemotre de Serge, ajouter la fonction sans fil.
Bouton sans fil, personnaliser la fonction depuis le module configuration ou en hard s'il reste une entrée. (Btn Next ou Event base)

Chrono version ++
l'écran pourrait être déporté sur la chaise du DC et passer sur un 10 ou 12". avec connecteur hdmi, usb et alimentation en facade, 
refaire la carte d'interface 
refaire un boitier

**Comment by jomarin38** [comment]
Quelques remarques supplémentaires :

Au moment de redémarrer le deuxième jour, il a fallu passer une manche en mettant 0 à tout le monde pour que le changement de pilote de départ soit pris en compte.
Cache soleil plus grand ?
Andreas propose de remplacer "In Start" par "Outside" dans les sons.

**Chrono version +++**
Utiliser un écran transflectif pour une bonne lisibilité au soleil ?

**Ergonomie pour être utilisable par d'autres personnes que les développeurs :**
Lancer le soft automatiquement au démarrage du raspberry
Ajouter un bouton shutdown.

**Comment by jomarin38** [comment]
Utiliser des boutons physiques pour mettre des pénalités / revols / vol null ?
