### ISSUE TITLE
Starting competitor

### ISSUE THREAD

**Issue by sdaviet** [jomarin38/F3FChrono#52]
adding a numeric control in the contest data to choose which competitor start the run.

**Comment by jomarin38** [comment]
Yes you are right, it is clearly needed :-).
We could also add a button to affect it randomly and start the round.

**Comment by sdaviet** [comment]
sql commands :
ALTER TABLE `f3f_chrono`.`event` ADD COLUMN `bib_start` INT NULL DEFAULT 0 AFTER `max_interruption_time`, ADD COLUMN `revol` INT NULL DEFAULT 5 AFTER `bib_start`;

**Comment by sdaviet** [comment]
sql commands
ALTER TABLE `f3f_chrono`.`event` 
ADD COLUMN `dayduration` INT NULL DEFAULT 1 AFTER `flights_before_refly`;
